version: '3'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GAGGIUINO_BASE_URL=http://gaggiuino.local
      - MCP_TRANSPORT_TYPE=http
      - SERVER_PORT=8080
      - REQUEST_TIMEOUT=5000
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - gaggiuino-network

networks:
  gaggiuino-network:
    driver: bridge